### ISSUE TITLE
OMG website, documents, explorer unexpected redirection

### ISSUE THREAD

**Issue by jtomtan** [omisego/dev-portal#77]
Hi,

I am Tom from Ownbit team. We are trying to integrate OMG network into Ownbit wallet (https://ownbit.io). Several problems we found:

If you try to browse OMG website, documents or explorer in China, you will always get unexpected redirection to https://omg.network/cn/. 

And in document: https://docs.omg.network/network/standard-exits, there's a mis-spelling: 3. Start a standart exit.

And is there any detail description for fees in the OMG network (by using OMG or ETH separately)?

Thanks.

**Comment by thisguy002** [comment]
Hey Tom, nice to meet you. Just in case, it's an old repository for the dev portal. The one we're using now is [this one](https://github.com/omgnetwork/omgnetwork.github.io). With regards to your questions:
1) I'll check what causes the redirect and let you know, it's more likely the Docusaurus default behavior.
2) Thanks for catching a typo. I'll include it with a few other ones with the next update.
3) There's [a separate document](https://docs.omg.network/network/fees) about the fees. Currently, mainnet uses OMG token as a fee, Ropsten uses ETH. Thus when you construct a transaction body, you'll have one of two scenarios:

A. Mainnet
```
 const transactionBody = await childChain.createTransaction({
    owner: "0x8CB0DE6206f459812525F2BA043b14155C2230C0",
    payments: [
      {
        owner: "0xA9cc140410c2bfEB60A7260B3692dcF29665c254",
        currency: OmgUtil.transaction.ETH_CURRENCY,
        amount: "350000000000000",
      },
    ],
    fee: {
      currency: 0xd26114cd6EE289AccF82350c8d8487fedB8A0C07
    },
    metadata: "data",
  });
```

B. Ropsten

```
 const transactionBody = await childChain.createTransaction({
    owner: "0x8CB0DE6206f459812525F2BA043b14155C2230C0",
    payments: [
      {
        owner: "0xA9cc140410c2bfEB60A7260B3692dcF29665c254",
        currency: OmgUtil.transaction.ETH_CURRENCY,
        amount: "350000000000000",
      },
    ],
    fee: {
      currency: OmgUtil.transaction.ETH_CURRENCY
    },
    metadata: "data",
  });
```

You can also join our [ODP program](https://docs.omg.network) (click `SIGN UP`) for more technical guidance on the integration.

**Comment by jtomtan** [comment]
Thanks for the quick response. 

ODP grogram signed up.
